#Part 1 Input(receiving values)
print("Please enter the following information:")
print("")
firstName = input("First name: ")
lastName = input("Last name: ")
emailAddress = input("Email address: ")
phoneNumber = input("Phone number: ")
jobTitle = input("Job title: ")
idNumber = input("ID Number: ")
print("")
#Part 2 Output(showing values)
print("The ID Card is:")
print("----------------------------------------")
print(f"{lastName.upper()}, {firstName.capitalize()}")
print(f"{jobTitle.title()}")
print(f"ID: {idNumber}")
print("")
print(emailAddress.lower())
print(phoneNumber)
print("----------------------------------------")


